// Generates src/internal/css.generated.ts from upstream CSS + src/styles/canvas.css.
// The BPMN font bytes are never modified: only the @font-face URL base is rewritten
// in the generated string, and dist/styles.css is produced by build-assets.mjs.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const read = (p) => readFileSync(root + p, "utf8");

const fontCss = read("node_modules/bpmn-js/dist/assets/bpmn-font/css/bpmn.css");
const fontFace = /@font-face\s*\{[^}]*\}/.exec(fontCss)?.[0];
if (!fontFace) throw new Error("bpmn-font @font-face block not found");
const iconRules = fontCss
  .replace(/@charset[^;]*;/, "")
  .replace(fontFace, "")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .trim();

import { existsSync } from "node:fs";
const legendCss = ["legend-palette.css", "palette-colors.css", "workshop.css", "workshop-shell.css"].map((f) => (existsSync(root + "src/styles/" + f) ? read("src/styles/" + f) : "")).join("\n");
const base = [
  read("node_modules/diagram-js/assets/diagram-js.css"),
  read("node_modules/bpmn-js/dist/assets/bpmn-js.css"),
  iconRules,
  read("src/styles/canvas.css"),
  legendCss,
].join("\n");

// data: URIs (legend palette glyphs, upstream breadcrumb arrow) become files shipped under
// dist/assets/inline/, so a strict CSP needs no `data:` source and a CDN serves them like the fonts.
// The CSS keeps a placeholder per file; the runtime resolves it with one literal
// `new URL(..., import.meta.url)` per file (see assets.generated.ts), which bundlers can detect.
const ASSET = "__ASSET__";
const inlineDir = root + ".gen/inline/";
rmSync(inlineDir, { recursive: true, force: true });
mkdirSync(inlineDir, { recursive: true });
const inlineFiles = new Map();
function decodeDataUri(uri) {
  const comma = uri.indexOf(",");
  const meta = uri.slice(5, comma);
  const payload = uri.slice(comma + 1);
  if (!/^image\/svg\+xml/.test(meta)) throw new Error("unexpected data: URI type " + meta);
  if (/;base64/.test(meta)) return Buffer.from(payload, "base64").toString("utf8");
  try { return decodeURIComponent(payload); } catch { return payload; }
}
function extractDataUris(css) {
  let out = "";
  let at = 0;
  for (;;) {
    const i = css.indexOf("url(", at);
    if (i < 0) break;
    let j = i + 4;
    const quote = css[j] === "'" || css[j] === '"' ? css[j] : "";
    if (quote) j++;
    if (!css.startsWith("data:", j)) { out += css.slice(at, i + 4); at = i + 4; continue; }
    const end = quote ? css.indexOf(quote, j) : css.indexOf(")", j);
    if (end < 0) throw new Error("unterminated url(data:...)");
    const svg = decodeDataUri(css.slice(j, end).replace(/\\"/g, '"'));
    let name = [...inlineFiles].find(([, v]) => v === svg)?.[0];
    if (!name) {
      name = `inline-${String(inlineFiles.size + 1).padStart(2, "0")}.svg`;
      inlineFiles.set(name, svg);
    }
    out += css.slice(at, i + 4) + (quote || '"') + ASSET + name + (quote || '"');
    at = quote ? end + 1 : end;
  }
  return out + css.slice(at);
}
const baseNoData = extractDataUris(base);
if (/data:/.test(baseNoData.replace(/data-[a-z-]+/g, ""))) throw new Error("a data: URI is left in the CSS");
for (const [name, svg] of inlineFiles) writeFileSync(inlineDir + name, svg);
const assetsTs = `// Generated by scripts/gen-css.mjs. Do not edit.
/** URL of each file under dist/assets/inline/, one literal per file so bundlers emit them. */
export function inlineAssetUrls(): Record<string, string> {
  return {
${[...inlineFiles.keys()].sort().map((n) => `    "${n}": new URL("../assets/inline/${n}", import.meta.url).href,`).join("\n")}
  };
}
`;
writeFileSync(root + "src/internal/assets.generated.ts", assetsTs);

const FONT_BASE = "__FONT_BASE__";
const runtimeFontFace = fontFace.replaceAll("../font/", FONT_BASE);

const out = `// Generated by scripts/gen-css.mjs. Do not edit.
export const FONT_BASE_PLACEHOLDER = ${JSON.stringify(FONT_BASE)};
export const ASSET_PLACEHOLDER = ${JSON.stringify(ASSET)};
export const BASE_CSS = ${JSON.stringify(baseNoData)};
export const FONT_FACE_CSS = ${JSON.stringify(runtimeFontFace)};
`;
writeFileSync(root + "src/internal/css.generated.ts", out);
console.log(`css.generated.ts: base ${baseNoData.length} bytes, font-face ${runtimeFontFace.length} bytes, ${inlineFiles.size} data: URI(s) moved to files`);
