// Generates src/internal/css.generated.ts from upstream CSS + src/styles/canvas.css.
// The BPMN font bytes are never modified: only the @font-face URL base is rewritten
// in the generated string, and dist/styles.css is produced by build-assets.mjs.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const read = (p) => readFileSync(root + p, "utf8");

const fontCss = read("node_modules/bpmn-js/dist/assets/bpmn-font/css/bpmn.css");
const fontFace = /@font-face\s*\{[^}]*\}/.exec(fontCss)?.[0];
if (!fontFace) throw new Error("bpmn-font @font-face block not found");
const iconRules = fontCss
  .replace(/@charset[^;]*;/, "")
  .replace(fontFace, "")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .trim();

import { existsSync } from "node:fs";
const legendCss = existsSync(root + "src/styles/legend-palette.css") ? read("src/styles/legend-palette.css") : "";
const base = [
  read("node_modules/diagram-js/assets/diagram-js.css"),
  read("node_modules/bpmn-js/dist/assets/bpmn-js.css"),
  iconRules,
  read("src/styles/canvas.css"),
  legendCss,
].join("\n");

const FONT_BASE = "__FONT_BASE__";
const runtimeFontFace = fontFace.replaceAll("../font/", FONT_BASE);

const out = `// Generated by scripts/gen-css.mjs. Do not edit.
export const FONT_BASE_PLACEHOLDER = ${JSON.stringify(FONT_BASE)};
export const BASE_CSS = ${JSON.stringify(base)};
export const FONT_FACE_CSS = ${JSON.stringify(runtimeFontFace)};
`;
writeFileSync(root + "src/internal/css.generated.ts", out);
console.log(`css.generated.ts: base ${base.length} bytes, font-face ${runtimeFontFace.length} bytes`);
